# Generated by Django 4.0.5 on 2022-06-08 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kakao_id', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('nickname', models.CharField(max_length=50)),
                ('thumbnail_url', models.URLField(max_length=600)),
                ('point', models.PositiveIntegerField(default=10000000)),
                ('shoe_size', models.CharField(max_length=20, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('email_subscription', models.BooleanField(default=False)),
                ('sms_subscription', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
