# Generated by Django 4.0.5 on 2022-06-12 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_release_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductCateogory',
            new_name='ProductCategory',
        ),
    ]
